package org.fluentjava.iwant.api.javamodules;

public enum CodeStyle {

	ANNOTATION_SUPER_INTERFACE,

	ASSERT_IDENTIFIER,

	AUTOBOXING,

	COMPARING_IDENTICAL,

	DEAD_CODE,

	DEPRECATION,

	DEPRECATION_IN_DEPRECATED_CODE,

	DEPRECATION_WHEN_OVERRIDING_DEPRECATED_METHOD,

	DISCOURAGED_REFERENCE,

	EMPTY_STATEMENT,

	ENUM_IDENTIFIER,

	FALLTHROUGH_CASE,

	FATAL_OPTIONAL_ERROR,

	FIELD_HIDING,

	FINAL_PARAMETER_BOUND,

	FINALLY_BLOCK_NOT_COMPLETING_NORMALLY,

	FORBIDDEN_REFERENCE,

	HIDDEN_CATCH_BLOCK,

	INCLUDE_NULL_INFO_FROM_ASSERTS,

	INCOMPATIBLE_NON_INHERITED_INTERFACE_METHOD,

	INCOMPLETE_ENUM_SWITCH,

	INDIRECT_STATIC_ACCESS,

	LOCAL_VARIABLE_HIDING,

	METHOD_WITH_CONSTRUCTOR_NAME,

	MISSING_DEFAULT_CASE,

	MISSING_DEPRECATED_ANNOTATION,

	MISSING_HASHCODE_METHOD,

	MISSING_OVERRIDE_ANNOTATION,

	MISSING_OVERRIDE_ANNOTATION_FOR_INTERFACE_METHOD_IMPLEMENTATION,

	MISSING_SERIAL_VERSION,

	MISSING_SYNCHRONIZED_ON_INHERITED_METHOD,

	NO_EFFECT_ASSIGNMENT,

	NO_IMPLICIT_STRING_CONVERSION,

	NON_EXTERNALIZED_STRING_LITERAL,

	NULL_REFERENCE,

	OVERRIDING_PACKAGE_DEFAULT_METHOD,

	PARAMETER_ASSIGNMENT,

	POSSIBLE_ACCIDENTAL_BOOLEAN_ASSIGNMENT,

	POTENTIALLY_UNCLOSED_CLOSEABLE,

	POTENTIAL_NULL_REFERENCE,

	RAW_TYPE_REFERENCE,

	REDUNDANT_NULL_CHECK,

	REDUNDANT_SPECIFICATION_OF_TYPE_ARGUMENTS,

	REDUNDANT_SUPERINTERFACE,

	REPORT_METHOD_CAN_BE_POTENTIALLY_STATIC,

	REPORT_METHOD_CAN_BE_STATIC,

	SPECIAL_PARAMETER_HIDING_FIELD,

	STATIC_ACCESS_RECEIVER,

	SUPPRESS_OPTIONAL_ERRORS,

	SUPPRESS_WARNINGS,

	SYNTHETIC_ACCESS_EMULATION,

	TYPE_PARAMETER_HIDING,

	UNAVOIDABLE_GENERIC_TYPE_PROBLEMS,

	UNCHECKED_TYPE_OPERATION,

	UNCLOSED_CLOSEABLE,

	UNDOCUMENTED_EMPTY_BLOCK,

	UNHANDLED_WARNING_TOKEN,

	UNNECESSARY_ELSE,

	UNNECESSARY_TYPE_CHECK,

	UNQUALIFIED_FIELD_ACCESS,

	UNUSED_DECLARED_THROWN_EXCEPTION,

	UNUSED_DECLARED_THROWN_EXCEPTION_EXEMPT_EXCEPTION_AND_THROWABLE,

	UNUSED_DECLARED_THROWN_EXCEPTION_INCLUDE_DOC_COMMENT_REFERENCE,

	UNUSED_DECLARED_THROWN_EXCEPTION_WHEN_OVERRIDING,

	UNUSED_IMPORT,

	UNUSED_LABEL,

	UNUSED_LOCAL,

	UNUSED_OBJECT_ALLOCATION,

	UNUSED_PARAMETER,

	UNUSED_PARAMETER_INCLUDE_DOC_COMMENT_REFERENCE,

	UNUSED_PARAMETER_WHEN_IMPLEMENTING_ABSTRACT,

	UNUSED_PARAMETER_WHEN_OVERRIDING_CONCRETE,

	UNUSED_PRIVATE_MEMBER,

	UNUSED_TYPE_PARAMETER,

	UNUSED_WARNING_TOKEN,

	VARARGS_ARGUMENT_NEED_CAST,

}
