# TODO maybe iwant will handle all this "refresh stuff"...
rm -rf iwant/cached
iwant/as_shell-user/to-bootstrap-iwant.sh && iwant/as-iwant-user/to-develop-iwant.sh && iwant/as-iwant-developer/target/local-website/as-path
